springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8080

app:
  base-url: ${BASE_URL:http://localhost:8080}

# JWT settings
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidation12345678901234567890}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour 기본 값 추가

spring:
  # OAuth2 settings
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET} # 필요하면 redirect-uri 변경하기
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: Google
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: create # 개발 중 schema 변경이 잦으므로 create -> 이후 데이터를 보존하려면 update로 변경하기
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:false}