springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
server:
  port: 8080

app:
  base-url: ${BASE_URL:http://localhost:8080}

spring:
  # OAuth2 settings
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET} # 필요하면 redirect-uri 변경하기
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: email

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:false}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000 # 1 hour
  refresh-token-expiration: 1209600000 # 14 days