name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Java 설정
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 빌드
      - name: Build
        run: ./gradlew build -x test

      # 4. Docker 이미지 빌드 및 푸시
#      - name: Build Docker image
#        run: |
#          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
#          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 5. 서버에 배포
#      - name: Deploy to server
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
#            docker stop myapp || true
#            docker rm myapp || true
#            docker run -d --name myapp -p 8080:8080 \
#              -e SPRING_PROFILES_ACTIVE=prod \
#              -e DB_URL="${{ secrets.DB_URL }}" \
#              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
#              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
#              ${{ secrets.DOCKER_USERNAME }}/myapp:latest